CREATE TABLE IF NOT EXISTS branches (
    id BIGSERIAL PRIMARY KEY,

    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE RESTRICT,

    name VARCHAR(64) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,

    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    UNIQUE (store_id, name)
);
